# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYUiuA6etWdxqJvQmS3_MG9Gzwki3DLK
"""

# Google Colab uchun dastur

# Foydalanuvchidan matnni olish
user_input = input("Iltimos, matn kiriting: ")

# Matnni so'zlarga ajratish
words = user_input.split()

# So'zlar sonini hisoblash
num_words = len(words)

# Natijani chiqarish
print(f"Matndagi so'zlar soni: {num_words}")